language: java

jdk:
  - oraclejdk8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y unzip build-essential git libx11-dev libxt-dev libraw1394-dev libavc1394-dev libiec61883-dev libfreetype6-dev yasm autoconf libtool libaudio-dev libpulse-dev libasound-dev

script:
  - export JDK_HOME=$JAVA_HOME
  - export JAVA_ARCH=amd64
  - cd build
  - ./buildall.sh
  - cd ..

deploy:
  skip_cleanup: true
  provider: script
  script: build/deploy.sh
  on:
    branch: master

